icon_spinner_still = I(_class='fa', _style="display:none")
icon_add = I(_class='fa fa-plus')
icon_primary_papers = I(_class='fa fa-check-circle-o')
icon_all_papers = I(_class='fa fa-circle-o')
icon_pick_review = SPAN(I(_class='fa fa-align-right'), I(_class='fa fa-align-left'))
